#ifndef LUMS_INCLUDED_OPENGL_ABI_H
#define LUMS_INCLUDED_OPENGL_ABI_H

#include <Lums/Util/Common.h>

#if defined(LUMS_BUILD_OPENGL)
# define LUMS_API_OPENGL LUMS_DLLEXPORT
#else
# define LUMS_API_OPENGL LUMS_DLLIMPORT
#endif

#endif /* LUMS_INCLUDED_OPENGL_ABI_H */
