name: Doxygen

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Doxygen Generation
        uses: mattnotmitt/doxygen-action@v1

      - name: Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html
